name: C# Fundamentals - Pluralsight

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore csharp_fundamentals.sln
    - name: Build
      run: dotnet build csharp_fundamentals.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test csharp_fundamentals.sln --no-restore --verbosity normal
